Change the GetLogger function from Mutex to RWMutex
TarsCloud/TarsGo pull request #277
Opened 2021-03-31 11:23 UTC by tangyouyou

Change the GetLogger function from Mutex to RWMutex

2021-03-31 11:42 UTC, chenhengqi reviewed
What's the point of this change?

2021-03-31 13:14 UTC, tangyouyou commented
> What's the point of this change?

RWMutex is faster than Mutex, See pictures for more details.
![RMMutex](https://user-images.githubusercontent.com/13697036/113149852-0994d380-9266-11eb-9920-b9fdc5239d64.png)

2021-03-31 14:35 UTC, chenhengqi commented
> > What's the point of this change?
> 
> RWMutex is faster than Mutex, See pictures for more details.
> ![RMMutex](https://user-images.githubusercontent.com/13697036/113149852-0994d380-9266-11eb-9920-b9fdc5239d64.png)

Performance isn't an issue in this case.

2021-03-31 14:41 UTC, chenhengqi requested changes

2021-03-31 14:41 UTC, chenhengqi commented on tars/util/rogger/logger.go
> +		ok = false
use `var ok bool` instead

2021-03-31 14:41 UTC, chenhengqi commented on tars/util/rogger/logger.go
> +	if lg, ok = loggerMap[name]; ok == false {
use `!ok` instead

2021-03-31 14:41 UTC, chenhengqi commented on tars/util/rogger/logger.go
> +			name:   name,
missing the `writer` field

2021-06-19 12:33 UTC, defool commented
应该在初始化时GetLogger，而不是每次打日志都调用，这样的话性能不是问题。
先关闭这个pr，如果有需要可以重新打开。

2021-06-19 12:33 UTC, closed without merging