Fix nil map
TarsCloud/TarsGo pull request #284
Opened 2021-04-28 09:31 UTC by tzwsoho

修正map没有初始化而直接使用时报assignment to entry in nil map错误的问题

2021-04-28 15:02 UTC, chenhengqi requested changes

2021-04-28 15:02 UTC, chenhengqi commented on tars/tools/tars2go/gen_go.go
> +			c.WriteString(" = make(map[" + gen.genType(v.Type.TypeK) + "]" + gen.genType(v.Type.TypeV) + ")\n")
Consider replace this with `gen.genType(v.Type)`.

2021-04-28 15:03 UTC, chenhengqi commented
Squash your commits please.

2021-04-29 02:01 UTC, tzwsoho commented
> Squash your commits please.

Done

2021-04-29 02:40 UTC, chenhengqi commented
> > Squash your commits please.
> 
> Done

I mean you should combine all the commits into one, they are not relative.

2021-04-29 02:47 UTC, closed without merging