feat: zipkin 支持上报具体的 obj，支持 http server，支持 kafka 和 http 上报，支持采样率
TarsCloud/TarsGo pull request #373
Opened 2022-07-13 10:52 UTC by phpcyy

fix #372 .

2022-07-13 13:46 UTC, lbbniu commented
可以把对应的zipkin examples 同时调整下吗

2022-07-14 04:13 UTC, phpcyy commented
> 可以把对应的zipkin examples 同时调整下吗

已调整

2022-07-16 10:15 UTC, lbbniu commented
<img width="595" alt="image" src="https://user-images.githubusercontent.com/6211983/179350632-e629403d-02cc-4dd9-abd8-b2f852e8afd0.png">
这个可以看到吗？ 辛苦同步修改下

2022-07-17 01:24 UTC, phpcyy commented
> <img alt="image" width="595" src="https://user-images.githubusercontent.com/6211983/179350632-e629403d-02cc-4dd9-abd8-b2f852e8afd0.png">
> 
> 这个可以看到吗？ 辛苦同步修改下

改了

2022-07-18 05:03 UTC, lbbniu commented
Please squash the commits before merge.

2022-07-18 05:49 UTC, lbbniu requested changes

2022-07-18 05:51 UTC, lbbniu requested changes

2022-07-18 05:51 UTC, lbbniu commented on tars/plugin/zipkintracing/zipkintracing.go
> +func Init(
revert please

2022-07-18 07:14 UTC, merged